# config/_default/languages.en.toml

title = "A Semi-Techy Blog"

[params.author]
name = "Joshua Ross"
image = "img/author.jpg"
headline = "amateur automation,Linux and wow nerd."
bio = "amateur automation,Linux and wow nerd."
links = [
{ email = "mailto:contact@rossjm.dev" },
{ github = "https://github.com/jershbytes" },
{ bluesky = "https://bsky.app/profile/rossjm.net" },
{ linkedin = "https://www.linkedin.com/in/joshuamalcom/" },
{ steam= "https://steamcommunity.com/id/jershbytes" },
]
