
[[main]]
name = "About"
pageRef = "about.md"
weight = 10

[[main]]
name = "Blog"
pageRef = "posts"
weight = 20

[[main]]
name = "Links"
url = "https://links.rossjm.net/@Jersh"
weight = 30

[[main]]
identifier = "search"
weight = 99
    [main.params]
    action = "search"
    icon = "search"
